### ISSUE TITLE
[BUG] Could not connect

### ISSUE THREAD

**Issue by mzch** [DaneeSkripter/DaneeCloud#41]
**Describe the bug**
When `npm start`, an error happens:
```
[19.05.2023 | 21:09:10] [SUCCESS] Server listening on port 5026
/srv/danee/DaneeCloud/node_modules/discord-rpc/src/transports/ipc.js:32
        reject(new Error('Could not connect'));
               ^

Error: Could not connect
    at Socket.onerror (/srv/danee/DaneeCloud/node_modules/discord-rpc/src/transports/ipc.js:32:16)
    at Object.onceWrapper (node:events:628:26)
    at Socket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on RP instance at:
    at /srv/danee/DaneeCloud/node_modules/discord-rich-presence/index.js:65:28
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.16.0
```

**To Reproduce**
1. `npm install`
2. `npm start`

**Expected behavior**
Start successfully.

**Additional context**
What are `richpresenceclientid` and `richpresencelogo`? No document describes them at all.

**Comment by DaneeSkripter** [comment]
Hello @mzch,
thank you for creating issue, it's fixed now. *Discord rich presence was bad idea because you will have to open discord when starting the dashboard.* So, I completely removed it, to fix this bug please download the latest version or execute ```git pull```.
**I see you liked this project, it would make me very happy if you share this project with others 💖**
